// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package handler

import (
	"net/http"

	"app/oidc/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/authorize",
				Handler: AuthorizeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/logout",
				Handler: EndSessionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/revoke",
				Handler: RevokeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/token",
				Handler: TokenHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/userinfo",
				Handler: UserInfoHandler(serverCtx),
			},
		},
	)
}
